name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like
      placeholder: "I would like to add..."
    validations:
      required: true
  
  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Use Case
      description: Why would this feature be useful?
      placeholder: "This would help with..."
    validations:
      required: true
  
  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: How could this be implemented?
      placeholder: "One approach could be..."
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches?
      placeholder: "Other options..."
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other details
      placeholder: "Additional context here..."
